# This file is used to configure the Process-PSModule workflow.
# Reference:
# - https://github.com/PSModule/Process-PSModule?tab=readme-ov-file#configuration
Test:
  SourceCode:
    Skip: true
  PSModule:
    Skip: true
  Module:
    MacOS:
      Skip: true
    Windows:
      Skip: true
  TestResults:
    Skip: true
  CodeCoverage:
    Skip: true
    PercentTarget: 0
Build:
  Docs:
    Skip: true
